# Form implementation generated from reading ui file 'buoi4_Qt.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 500)

        # Support both QMainWindow and QWidget as parent
        if isinstance(MainWindow, QtWidgets.QMainWindow):
            self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            MainWindow.setCentralWidget(self.centralwidget)
        else:
            self.centralwidget = MainWindow
            layout = QtWidgets.QVBoxLayout(MainWindow)
            layout.setContentsMargins(0, 0, 0, 0)
            container = QtWidgets.QWidget(parent=MainWindow)
            container.setObjectName("centralwidget")
            layout.addWidget(container)
            self.centralwidget = container

        self.card = QtWidgets.QFrame(parent=self.centralwidget)
        self.card.setGeometry(QtCore.QRect(210, 85, 300, 330))
        self.card.setObjectName("card")
        self.labelTitle = QtWidgets.QLabel(parent=self.card)
        self.labelTitle.setGeometry(QtCore.QRect(0, 20, 300, 40))
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.lineEmail = QtWidgets.QLineEdit(parent=self.card)
        self.lineEmail.setGeometry(QtCore.QRect(40, 90, 220, 34))
        self.lineEmail.setObjectName("lineEmail")
        self.linePassword = QtWidgets.QLineEdit(parent=self.card)
        self.linePassword.setGeometry(QtCore.QRect(40, 145, 220, 34))
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.linePassword.setObjectName("linePassword")
        self.checkRemember = QtWidgets.QCheckBox(parent=self.card)
        self.checkRemember.setGeometry(QtCore.QRect(40, 190, 200, 20))
        self.checkRemember.setObjectName("checkRemember")
        self.btnLogin = QtWidgets.QPushButton(parent=self.card)
        self.btnLogin.setGeometry(QtCore.QRect(40, 225, 220, 40))
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.labelCreate = QtWidgets.QLabel(parent=self.card)
        self.labelCreate.setGeometry(QtCore.QRect(40, 280, 110, 20))
        self.labelCreate.setObjectName("labelCreate")
        self.labelCreate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.labelForgot = QtWidgets.QLabel(parent=self.card)
        self.labelForgot.setGeometry(QtCore.QRect(155, 280, 120, 20))
        self.labelForgot.setObjectName("labelForgot")
        self.labelForgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        # Tab order
        MainWindow.setTabOrder(self.lineEmail, self.linePassword)
        MainWindow.setTabOrder(self.linePassword, self.checkRemember)
        MainWindow.setTabOrder(self.checkRemember, self.btnLogin)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - LỜI NHẮC"))
        # Transparent background - gradient comes from the parent QStackedWidget
        MainWindow.setStyleSheet(_translate("MainWindow",
            "background: transparent;"))
        self.card.setStyleSheet(_translate("MainWindow", "\n"
"QFrame{\n"
" background:white;\n"
" border-radius:20px;\n"
"}\n"
"     "))
        self.labelTitle.setStyleSheet(_translate("MainWindow", "\n"
"font-size:22px;\n"
"font-weight:bold;\n"
"color:#0b4f6c;\n"
"      "))
        self.labelTitle.setText(_translate("MainWindow", "\u0110\u0102NG NH\u1eacP"))
        self.lineEmail.setStyleSheet(_translate("MainWindow", "\n"
"QLineEdit{\n"
" border:none;\n"
" border-bottom:2px solid #999;\n"
" font-size:14px;\n"
" color:black;\n"
" padding:5px;\n"
"}\n"
"QLineEdit:focus{\n"
" border-bottom:2px solid #0b4f6c;\n"
"}\n"
"      "))
        self.lineEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.linePassword.setStyleSheet(_translate("MainWindow", "\n"
"QLineEdit{\n"
" border:none;\n"
" border-bottom:2px solid #999;\n"
" font-size:14px;\n"
" color: black;\n"
" padding:5px;\n"
"}\n"
"QLineEdit:focus{\n"
" border-bottom:2px solid #0b4f6c;\n"
"}\n"
"      "))
        self.linePassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkRemember.setStyleSheet(_translate("MainWindow", "color:#333;"))
        self.checkRemember.setText(_translate("MainWindow", "Remember me"))
        self.btnLogin.setStyleSheet(_translate("MainWindow", "\n"
"QPushButton{\n"
" background:#0b4f6c;\n"
" color:white;\n"
" font-size:15px;\n"
" border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
" background:#11998e;\n"
"}\n"
"QPushButton:pressed{\n"
" background:#0e7c73;\n"
"}\n"
"      "))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.labelCreate.setStyleSheet(_translate("MainWindow",
            "color:#0b4f6c; font-size:12px; text-decoration:underline;"))
        self.labelCreate.setText(_translate("MainWindow", "Create account"))
        self.labelForgot.setStyleSheet(_translate("MainWindow",
            "color:#0b4f6c; font-size:12px; text-decoration:underline;"))
        self.labelForgot.setText(_translate("MainWindow", "Forgot password?"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
