# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 500)

        # Support both QMainWindow and QWidget as parent
        if isinstance(MainWindow, QtWidgets.QMainWindow):
            self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            MainWindow.setCentralWidget(self.centralwidget)
        else:
            self.centralwidget = MainWindow
            layout = QtWidgets.QVBoxLayout(MainWindow)
            layout.setContentsMargins(0, 0, 0, 0)
            container = QtWidgets.QWidget(parent=MainWindow)
            container.setObjectName("centralwidget")
            layout.addWidget(container)
            self.centralwidget = container

        self.card = QtWidgets.QFrame(parent=self.centralwidget)
        self.card.setGeometry(QtCore.QRect(210, 20, 300, 451))
        self.card.setObjectName("card")
        self.labelTitle = QtWidgets.QLabel(parent=self.card)
        self.labelTitle.setGeometry(QtCore.QRect(0, 20, 300, 40))
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")

        # Username label
        self.labelTitle_4 = QtWidgets.QLabel(parent=self.card)
        self.labelTitle_4.setGeometry(QtCore.QRect(30, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.labelTitle_4.setFont(font)
        self.labelTitle_4.setObjectName("labelTitle_4")

        self.lineUsername = QtWidgets.QLineEdit(parent=self.card)
        self.lineUsername.setGeometry(QtCore.QRect(30, 90, 220, 34))
        self.lineUsername.setObjectName("lineUsername")

        # Email label
        self.labelTitle_3 = QtWidgets.QLabel(parent=self.card)
        self.labelTitle_3.setGeometry(QtCore.QRect(30, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.labelTitle_3.setFont(font)
        self.labelTitle_3.setObjectName("labelTitle_3")

        self.lineEmail = QtWidgets.QLineEdit(parent=self.card)
        self.lineEmail.setGeometry(QtCore.QRect(30, 150, 220, 34))
        self.lineEmail.setObjectName("lineEmail")

        # Password label
        self.labelTitle_2 = QtWidgets.QLabel(parent=self.card)
        self.labelTitle_2.setGeometry(QtCore.QRect(30, 190, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.labelTitle_2.setFont(font)
        self.labelTitle_2.setObjectName("labelTitle_2")

        self.linePassword = QtWidgets.QLineEdit(parent=self.card)
        self.linePassword.setGeometry(QtCore.QRect(30, 210, 220, 34))
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.linePassword.setObjectName("linePassword")

        # Confirm Password label
        self.labelConfirm = QtWidgets.QLabel(parent=self.card)
        self.labelConfirm.setGeometry(QtCore.QRect(30, 250, 150, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.labelConfirm.setFont(font)
        self.labelConfirm.setObjectName("labelConfirm")

        self.lineConfirm = QtWidgets.QLineEdit(parent=self.card)
        self.lineConfirm.setGeometry(QtCore.QRect(30, 270, 220, 34))
        self.lineConfirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineConfirm.setObjectName("lineConfirm")

        self.checkTerms = QtWidgets.QCheckBox(parent=self.card)
        self.checkTerms.setGeometry(QtCore.QRect(30, 315, 220, 20))
        self.checkTerms.setObjectName("checkTerms")
        self.btnRegister = QtWidgets.QPushButton(parent=self.card)
        self.btnRegister.setGeometry(QtCore.QRect(30, 345, 220, 40))
        self.btnRegister.setObjectName("btnRegister")
        self.btnRegister.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.labelLogin = QtWidgets.QLabel(parent=self.card)
        self.labelLogin.setGeometry(QtCore.QRect(40, 395, 220, 41))
        self.labelLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.labelLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        # Tab order
        MainWindow.setTabOrder(self.lineUsername, self.lineEmail)
        MainWindow.setTabOrder(self.lineEmail, self.linePassword)
        MainWindow.setTabOrder(self.linePassword, self.lineConfirm)
        MainWindow.setTabOrder(self.lineConfirm, self.checkTerms)
        MainWindow.setTabOrder(self.checkTerms, self.btnRegister)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register - L\u1edcI NH\u1eaeC"))
        # Transparent background - gradient comes from the parent QStackedWidget
        MainWindow.setStyleSheet(_translate("MainWindow",
            "background: transparent;"))
        self.card.setStyleSheet(_translate("MainWindow", "\n"
"QFrame{\n"
" background:white;\n"
" border-radius:20px;\n"
"}\n"
"     "))
        self.labelTitle.setStyleSheet(_translate("MainWindow", "\n"
"font-size:22px;\n"
"font-weight:bold;\n"
"color:#0b4f6c;\n"
"      "))
        self.labelTitle.setText(_translate("MainWindow", "\u0110\u0102NG K\u00dd"))

        # Label styles - 12px, bold, left-aligned
        label_style = "\nfont-size:12px;\nfont-weight:bold;\ncolor:#0b4f6c;\n"
        self.labelTitle_4.setStyleSheet(_translate("MainWindow", label_style))
        self.labelTitle_4.setText(_translate("MainWindow", "Username"))
        self.labelTitle_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.labelTitle_3.setStyleSheet(_translate("MainWindow", label_style))
        self.labelTitle_3.setText(_translate("MainWindow", "Email"))
        self.labelTitle_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.labelTitle_2.setStyleSheet(_translate("MainWindow", label_style))
        self.labelTitle_2.setText(_translate("MainWindow", "Password"))
        self.labelTitle_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.labelConfirm.setStyleSheet(_translate("MainWindow", label_style))
        self.labelConfirm.setText(_translate("MainWindow", "Confirm Password"))
        self.labelConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)

        # Input field styles
        input_style = _translate("MainWindow", "\n"
"QLineEdit{\n"
" border:none;\n"
" border-bottom:2px solid #999;\n"
" font-size:14px;\n"
" color:black;\n"
" padding:5px;\n"
"}\n"
"QLineEdit:focus{\n"
" border-bottom:2px solid #0b4f6c;\n"
"}\n"
"      ")
        self.lineUsername.setStyleSheet(input_style)
        self.lineUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEmail.setStyleSheet(input_style)
        self.lineEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.linePassword.setStyleSheet(input_style)
        self.linePassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineConfirm.setStyleSheet(input_style)
        self.lineConfirm.setPlaceholderText(_translate("MainWindow", "Confirm Password"))

        self.checkTerms.setStyleSheet(_translate("MainWindow", "color:#333;"))
        self.checkTerms.setText(_translate("MainWindow", "I agree to the terms"))
        self.btnRegister.setStyleSheet(_translate("MainWindow", "\n"
"QPushButton{\n"
" background:#0b4f6c;\n"
" color:white;\n"
" font-size:15px;\n"
" border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
" background:#11998e;\n"
"}\n"
"QPushButton:pressed{\n"
" background:#0e7c73;\n"
"}\n"
"      "))
        self.btnRegister.setText(_translate("MainWindow", "Register"))
        self.labelLogin.setStyleSheet(_translate("MainWindow",
            "color:#0b4f6c; font-size:12px; text-decoration:underline;"))
        self.labelLogin.setText(_translate("MainWindow", "Already have an account? Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
